global using AutoMapper;
global using Company.Common.DTOs;
global using Company.Data.Contexts;
global using Company.Data.Entities;
global using Company.Data.Interfaces;
global using Company.Data.Services;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Company.API.Extensions;